-- Borrar tablas si existen (importante para tests repetidos)
--DROP TABLE IF EXISTS fish_captures;
--DROP TABLE IF EXISTS auth_users;
--DROP TABLE IF EXISTS users;
--
---- Tabla users
--CREATE TABLE IF NOT EXISTS users (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    username VARCHAR(50) UNIQUE NOT NULL,
--    full_name VARCHAR(100) NOT NULL,
--    email VARCHAR(100) UNIQUE NOT NULL
--);
--
---- Tabla auth_users
--CREATE TABLE IF NOT EXISTS auth_users (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    user_id BIGINT UNIQUE NOT NULL,
--    username VARCHAR(50) UNIQUE NOT NULL,
--    password VARCHAR(255) NOT NULL,
--    email VARCHAR(100) UNIQUE NOT NULL,
--    role VARCHAR(20) NOT NULL DEFAULT 'USER',
--    enabled BOOLEAN NOT NULL DEFAULT TRUE,
--    account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    last_login_at TIMESTAMP,
--    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--);
--
---- Tabla fish_captures
--CREATE TABLE IF NOT EXISTS fish_captures (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    user_id BIGINT NOT NULL,
--    fish_type VARCHAR(50) NOT NULL,
--    weight FLOAT NOT NULL,
--    capture_date DATE NOT NULL,
--    location VARCHAR(100),
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--);

---- Datos de ejemplo para usuarios
--INSERT INTO users (username, full_name, email) VALUES
--('jperez', 'Juan Pérez', 'jperez@ejemplo.com'),
--('amartin', 'Ana Martín', 'amartin@ejemplo.com');
--
---- Datos de ejemplo para capturas de peces
--INSERT INTO fish_captures (capture_date, created_at, fish_type, location, weight, user_id) VALUES
--('2025-09-25', '2025-09-25 10:00:00', 'Trucha', 'Río X', 2.5, 1),
--('2025-09-26', '2025-09-26 12:30:00', 'Lucioperca', 'Lago Y', 1.8, 2);

